ServerMonitoring/Controllers/SettingsController.cs
using Domain;
using Model;
using ServerMonitoring.Logic;
using ServerMonitoring.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace ServerMonitoring.Controllers
{
    [Authorize]
    public class SettingController : Controller
    {
        protected static readonly DomainFacade Facade = DomainFacade.Instance;
        private static readonly log4net.ILog log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        // GET: Settings
        [HttpPost]
        public ActionResult UpdateSetting(SettingsModel model)
        {
            if (ModelState.IsValid)
            {
                //Refactor this
                if (model.EventSettings != null)
                {
                    foreach (var setting in model.EventSettings)
                    {
                        Setting s = Facade.SettingDomainController.GetSettingById(setting.Id);
                        s.Value = setting.Value;
                        Facade.SettingDomainController.UpdateSetting(s);
                    }
                }
                if (model.ServerSettings != null)
                {
                    foreach (var setting in model.ServerSettings)
                    {
                        Setting s = Facade.SettingDomainController.GetSettingById(setting.Id);
                        s.Value = setting.Value;
                        Facade.SettingDomainController.UpdateSetting(s);
                    }
                }
                if (model.GraphSettings != null)
                {
                    foreach (var setting in model.GraphSettings)
                    {
                        Setting s = Facade.SettingDomainController.GetSettingById(setting.Id);
                        s.Value = setting.Value;
                        Facade.SettingDomainController.UpdateSetting(s);

                    }
                }
                if(model.EventTypes != null)
                {
                    foreach (var type in model.EventTypes)
                    {
                        EventType t = Facade.EventTypeDomainController.GetTypeById(type.Id);
                        t.PeakValue = type.PeakValue;
                        t.Notify = type.Notify;
                        t.Risk = type.Risk;
                        Facade.EventTypeDomainController.UpdateEventType(t);
                    }
                }

            }
            return RedirectToAction("Index", "Home");
        }


        [HttpGet]
        public ActionResult GetSettings()
        {

            SettingsModel model = new SettingLogic().GetSettings();
            return PartialView("~/Views/Settings/_SettingsDialog.cshtml", model);
        }
    }
}

ServerMonitoring/Views/Settings/_SettingsDialog.cshtml
@model ServerMonitoring.Models.SettingsModel


<div class="modal-header">
    <span class="close">&times;</span>
    <div style="display:inline-flex">
        <h4 class="modal-title" id="myModalLabel"><b>Settings</b> </h4>
    </div>
</div>
<div class="modal-body">
    <div class="row">
        <div class="col-md-12">
            <ul class="nav nav-tabs">
                <li class="active"><a href="#settingsGraph" data-toggle="tab">Graph</a></li>
                @*<li><a href="#settingsServer" data-toggle="tab">Server</a></li>*@
                <li><a href="#settingsEvent" data-toggle="tab">Event</a></li>
                @*<li><a href="#settingsEmail" data-toggle="tab">Email</a></li>*@
            </ul>
            @using (Ajax.BeginForm("UpdateSetting", "Setting",
        new AjaxOptions { HttpMethod = "POST", InsertionMode = InsertionMode.Replace, OnComplete = "Completed", },
        new { @id = "SettingsForm" }))
            {
                <div class="tab-content">
                    <div id="settingsGraph" class="tab-pane fade in active">
                        @Html.Partial("~/Views/Settings/_SettingsGraph.cshtml")
                    </div>
                    <div id="settingsEvent" class="tab-pane fade">
                        @Html.Partial("~/Views/Settings/_SettingsEvent.cshtml")
                    </div>
                    @*<div id="settingsEmail" class="tab-pane fade">
                        @Html.Partial("~/Views/Settings/_SettingsEmail.cshtml")
                    </div>*@

                    @*<div id="settingsServer" class="tab-pane fade">
       @Html.Partial("~/Views/Settings/_SettingsServer.cshtml")
    </div>*@

                </div>
            }
        </div>
    </div>

</div>
<div class="modal-footer">
    <a class="mybtn mybtn-default" id="cancelSettingBtn"><i class="fa fa-close"></i> Close</a>
    <a class="mybtn mybtn-default" id="saveSettingsBtn"><i class="fa fa-save"></i> Save</a>
</div>
<script>
    window.onclick = function (event) {
        var modal = $('#myModal');
        if (event.target == modal) {
            $('#myModal').css("display", "none");
        }
    };
    $(document).click(function (event) {
        if (!$(event.target).closest('#myModal').length) {
            if ($('#myModal').is(":visible")) {
                $('#myModal').hide();
            }
        }
    });


    $('.close').click(function (event) {
        $('#myModal').css("display", "none");
    });
    $('#cancelSettingBtn').click(function (event) {
        $('#myModal').css("display", "none");
    });

    $('#saveSettingsBtn').click(function (event) {
        event.preventDefault();
        $('#SettingsForm').submit();
    });
</script>






















































@*<div class="modal fade product_view" id="product_view">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <a href="#" data-dismiss="modal" class="class pull-right"><span class="glyphicon glyphicon-remove"></span></a>
                    <h3 class="modal-title">HTML5 is a markup language</h3>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-6 product_img">
                            <img src="http://img.bbystatic.com/BestBuy_US/images/products/5613/5613060_sd.jpg" class="img-responsive">
                        </div>
                        <div class="col-md-6 product_content">
                            <h4>Product Id: <span>51526</span></h4>
                            <div class="rating">
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                (10 reviews)
                            </div>
                            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
                            <h3 class="cost"><span class="glyphicon glyphicon-usd"></span> 75.00 <small class="pre-cost"><span class="glyphicon glyphicon-usd"></span> 60.00</small></h3>
                            <div class="row">
                                <div class="col-md-4 col-sm-6 col-xs-12">
                                    <select class="form-control" name="select">
                                        <option value="" selected="">Color</option>
                                        <option value="black">Black</option>
                                        <option value="white">White</option>
                                        <option value="gold">Gold</option>
                                        <option value="rose gold">Rose Gold</option>
                                    </select>
                                </div>
                                <!-- end col -->
                                <div class="col-md-4 col-sm-6 col-xs-12">
                                    <select class="form-control" name="select">
                                        <option value="">Capacity</option>
                                        <option value="">16GB</option>
                                        <option value="">32GB</option>
                                        <option value="">64GB</option>
                                        <option value="">128GB</option>
                                    </select>
                                </div>
                                <!-- end col -->
                                <div class="col-md-4 col-sm-12">
                                    <select class="form-control" name="select">
                                        <option value="" selected="">QTY</option>
                                        <option value="">1</option>
                                        <option value="">2</option>
                                        <option value="">3</option>
                                    </select>
                                </div>
                                <!-- end col -->
                            </div>
                            <div class="space-ten"></div>
                            <div class="btn-ground">
                                <button type="button" class="btn btn-primary"><span class="glyphicon glyphicon-shopping-cart"></span> Add To Cart</button>
                                <button type="button" class="btn btn-primary"><span class="glyphicon glyphicon-heart"></span> Add To Wishlist</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>*@

ServerMonitoring/Views/Settings/_SettingsEmail.cshtml
@model ServerMonitoring.Models.SettingsModel

@using Model

<div class="row">
    <div class="container">
        @Html.ListBoxFor(m => m.EmailRecipents, new SelectList(Model.EmailRecipents, "Id", "Email"))
        
        
        <input type="text" name="email" value="email" />
        <button class="btn btn-default">Add</button>



    </div>
</div>

ServerMonitoring/Views/Settings/_SettingsEvent.cshtml
@model ServerMonitoring.Models.SettingsModel
@using Model
<div class="yscroll-container">

    <i class="fa fa-question-circle pull-right" title="You will be notified when the system detects a value above the
                       peakvalue. The notify checkbox is whether you want to receive an email or not"></i>
    @{


        for (int i = 0; i < Model.EventTypes.Count; i++)
        {
            @Html.HiddenFor(m => m.EventTypes[i].Id)
            @Html.HiddenFor(m => m.EventTypes[i].Name)
            <div class="event-container">
                <div>
                    <p><b>@Model.EventTypes[i].Name</b></p>

                </div>
                @if (Model.EventTypes[i].Name != StaticStrings.ServerDown && Model.EventTypes[i].Name != StaticStrings.ServerUp) //server down/up have no peak value
                {
                    <div class="peakvalue-div">
                        <p>Peak value</p>
                        @Html.TextBoxFor(m => m.EventTypes[i].PeakValue, Model.EventTypes[i].PeakValue.ToString(),
 new { @class = "form-control", id = "editPeakValue", type = "number", @min="1"})
                        @Html.ValidationMessageFor(m => m.EventSettings[i].Value, "Please enter a valid interval",
 new { @class = "text-danger" })
                    </div>
                }
                <div class="notify-div">
                    <p>Notify</p>
                    @Html.CheckBoxFor(m => m.EventTypes[i].Notify,
  new { @checked = "checked" })
                </div>


                <div class="risk-div">
                    <p>Category</p>
                    @Html.DropDownListFor(
           model => model.EventTypes[i].Risk,
           new SelectList(
                  new List<Object>{
                       new { value = 1 , text = "Danger"  },
                       new { value = 2 , text = "Warning" },
                       new { value = 3 , text = "Healthy"}
                    },
                  "value",
                  "text",
                   Model.EventTypes[i].Risk
           ), new { @class = "form-control", id = "editRisk" }
        )

                </div>

            </div>

            if (Model.EventTypes.Count - 1 != i)
            {
                <br /><hr />
            }

        }

    }
</div>



<script>
    $(document).ready(function () {
        $(".dropdown-risk").on("change", function (val) {
            console.log($('.dropdown-risk').attr("data-id"));
            console.log($('.dropdown-risk').val()); //1,2,3

        });

    });
</script>

ServerMonitoring/Views/Settings/_SettingsGraph.cshtml
@model ServerMonitoring.Models.SettingsModel

@{
    for (int i = 0; i < Model.GraphSettings.Count; i++)
    {

        @Html.HiddenFor(m => m.GraphSettings[i].Id)
        @Html.HiddenFor(m => m.GraphSettings[i].Description)
        @Html.HiddenFor(m => m.GraphSettings[i].Name)
<p><b>@Model.GraphSettings[i].Description</b></p>
        <div class="interval-div">
            
            @Html.TextBoxFor(m => m.GraphSettings[i].Value, Model.GraphSettings[i].Value.ToString()
                   , new { @class = "form-control", id = "editValue", type = "number", @min = "0" })
            @Html.ValidationMessageFor(m => m.GraphSettings[i].Value, "Please enter a valid interval", new { @class = "text-danger" })
        <p> minutes</p>
        </div>
        if (Model.GraphSettings.Count - 1 != i)
        {
            <br /><hr />
        }
    }
}

ServerMonitoring/Views/Settings/_SettingsServer.cshtml
@model ServerMonitoring.Models.SettingsModel
@{
    for (int i = 0; i < Model.ServerSettings.Count; i++)
    {

        @Html.HiddenFor(m => m.ServerSettings[i].Id)
        @Html.HiddenFor(m => m.ServerSettings[i].Description)
        @Html.HiddenFor(m => m.ServerSettings[i].Name)  
              <p><b>@Model.ServerSettings[i].Description</b></p>
        <div class="interval-div">
           
            @Html.TextBoxFor(m => m.ServerSettings[i].Value, Model.ServerSettings[i].Value.ToString(), new { @class = "form-control", id = "editValue", type = "number", min = "1" })
            @Html.ValidationMessageFor(m => m.ServerSettings[i].Value, "Please enter a valid interval", new { @class = "text-danger" })
            <p> minutes</p>
        </div>
        if (Model.ServerSettings.Count - 1 != i)
        {
            <br /><hr />
            }
        }
}